version: 1
services:
  - type: web
    name: my-svelte-app
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: NODE_ENV
        value: "production"
