version: 1
services:
  - type: web
    name: my-svelte-app
    env: node
    buildCommand: |
      echo "Instalando dependencias..."
      npm install
      echo "Construyendo la aplicación..."
      npm run build
    startCommand: "npm run preview"
    envVars:
      - key: NODE_ENV
        value: "production"